# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy project
COPY server.py /app/

# Expose port
EXPOSE 8000

# Define the default command
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
